-- Profiles Table (Syncs with Auth)
create table public.profiles (
  id uuid references auth.users not null primary key,
  email text,
  name text,
  role text default 'USER',
  created_at timestamptz default now()
);

-- Posts Table
create table public.posts (
  id bigint generated by default as identity primary key,
  title text not null,
  content text,
  excerpt text, -- Short description for cards
  type text default 'GENERAL', -- GENERAL, STUDY, CONTINUE
  tags text[], -- Array of strings
  author_id uuid references public.profiles(id),
  created_at timestamptz default now(),
  updated_at timestamptz default now()
);

-- RLS Policies (Security)
alter table public.profiles enable row level security;
alter table public.posts enable row level security;

-- Profiles: Anyone can read, User can update own
create policy "Public profiles are viewable by everyone." on public.profiles for select using (true);
create policy "Users can insert their own profile." on public.profiles for insert with check (auth.uid() = id);
create policy "Users can update own profile." on public.profiles for update using (auth.uid() = id);

-- Posts: Anyone can read, Authenticated users can insert
create policy "Public posts are viewable by everyone." on public.posts for select using (true);
create policy "Authenticated users can insert posts." on public.posts for insert with check (auth.role() = 'authenticated');
create policy "Users can update own posts." on public.posts for update using (auth.uid() = author_id);

-- Trigger to create profile on signup
create or replace function public.handle_new_user() 
returns trigger as $$
begin
  insert into public.profiles (id, email, name)
  values (new.id, new.email, new.raw_user_meta_data->>'full_name');
  return new;
end;
$$ language plpgsql security definer;

create trigger on_auth_user_created
  after insert on auth.users
  for each row execute procedure public.handle_new_user();
